name: SyncCORE
version: 1.0.0
api: [3.0.0]
description: SyncPVP Core
main: Core\Core
author: JamesCOMMANDO xvqle<--Add your names here too

permission:
  core.mod:
    description: Perms for Moderation
    default: false

commands:
  test:
    description: Test command
